# fly.toml app configuration file generated for codstats-api on 2025-05-09T15:29:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'codstats-api'
primary_region = 'ewr'

[env]
	NODE_ENV = 'production'
	HOST = '0.0.0.0'
	PORT = 8080
	PROTOCOL = 'https'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
